### ISSUE TITLE
Why it could not keep nonTE sequences?

### ISSUE THREAD

**Issue by wangj2009** [4ureliek/Parsing-RepeatMasker-Outputs#5]
I use the command as: 
**perl parseRM.pl -i cae.fa.out -p -s -r Cae_TE_potenGen_NoCat_Lib.fa -v**
But no simple/tandem repeats in the output file: cae.fa.out.parseRM.summary.tab.

If I use the command as:  **perl parseRM.pl -i cae.fa.out -p -s all -v**, It could not run. The error infor is:
        --------------------------------------------------
        --- Script parseRM.pl started (v5.8), with:
                - Input file = cae.fa.out
                 - Non TE repeats won't be filtered out (-simple all chosen)
               => global parsing will be done, with following options:
                 - no options
        --------------------------------------------------
             --- Prepping steps for --parse...
            --- Now parsing RM output(s)
                  -> ./cae.fa.out..
                  ..loading in array..
            **Can't use an undefined value as a SCALAR reference at parseRM.pl line 276, <$fh> line 4.**
So what's the problem, what mistakes we had?

Thank you very much!

Another question: **Is cae.fa.out or cae.fa.align better to get the total lenth annotated as each repeat, including the simple and tandem repeats?**

**Comment by 4ureliek** [comment]
Hi, can you try the version I just pushed? Should be good now.
For simple repeats, using the .out is probably very similar to the .align and it will run faster.
Cheers,
Aurelie

**Comment by wangj2009** [comment]
Hi Aurelie, thank you so much . But still have the same problem after I downloaded the new version.

./parseRM.pl -i *.fa.out -p -s all -v

--------------------------------------------------
 --- Script parseRM.pl started (v5.8.1), with:
      - Input file = *.fa.out
      - Non TE repeats won't be filtered out (--simple all chosen)
      => global parsing will be done, with following options:
         - no options
--------------------------------------------------
 --- Prepping steps for --parse...
 --- Now parsing RM output(s)
     -> ./Reads_trim_Pear_marked_simple_addLength_unalignMt_renameTE.fa.out..
        ..loading in array..
**Can't use an undefined value as a SCALAR reference at ./parseRM.pl line 277, <$fh> line 3.

**Comment by 4ureliek** [comment]
Hi,
Ha, sorry about that - please clone again, it will work this time!
Also, I am pretty sure that the code won't work with the * in the input file.
